### ISSUE TITLE
What does merging a proposal mean?

### ISSUE THREAD

**Issue by bergmark** [haskellfoundation/stability#8]
We have merged some (explicit) WIP-proposals, and the GHC.X.Hackage proposal so far.

What does it mean when a proposal gets merged?

**Comment by bergmark** [comment]
We covered this at our meeting. This is a staging area where the WG can work on ideas. If we reach a point where we are happy with a proposal, then we hope to submit them to another specific forum, such as making it a GHC or HF Tech Track proposal.

**Comment by goldfirere** [comment]
https://github.com/haskellfoundation/stability/issues/8#issuecomment-1047087604 is really helpful. Should it go in the README somewhere?
